ingress:
  enabled: true
  domain: "test"

frontend:
  image:
    registry: "ghcr.io/alliander-opensource"
    name: "pokertool-frontend"
    tag: "v1.0.1"
  replicas: 1
  resources:
    requests:
      cpu: "10m"
      memory: "15Mi"
    limits:
      cpu: "20m"
      memory: "30Mi"

backend:
  image:
    registry: "ghcr.io/alliander-opensource"
    name: "pokertool-backend"
    tag: "v1.0.0"
  replicas: 1
  resources:
    requests:
      cpu: "10m"
      memory: "200Mi"
    limits:
      cpu: "50m"
      memory: "200Mi"
