apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokertool-backend
  labels:
    app.kubernetes.io/name: pokertool
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: pokertool
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pokertool
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: pokertool-backend
          {{- with .Values.backend.image}}
          image: "{{ .registry }}/{{ .name }}:{{ .tag }}"
          {{- end }}
          ports:
            - containerPort: 8080
