apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}-backend
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "common.labels.standard" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    spec:
      containers:
        {{- with .Values.backend.image}}
        - image: "{{ .registry }}/{{ .name }}:{{ .tag }}"
        {{- end }}
          name: {{ template "common.names.fullname" . }}-backend
          ports:
            - containerPort: 8080
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: backend
