apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "common.names.fullname" . }}-backend
  labels:
    {{- include "common.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: backend
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - backend:
              service:
                name: {{ template "common.names.fullname" . }}-backend
                port:
                  number: 80
            path: /api
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: {{ template "common.names.fullname" . }}-backend-cert
