apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokertool-frontend
  labels:
    app.kubernetes.io/name: pokertool
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: pokertool
      app.kubernetes.io/component: frontend
  template:
    spec:
      containers:
        - name: pokertool-frontend
        {{- with .Values.frontend.image }}
          image: "{{ .registry }}/{{ .name }}:{{ .tag }}"
        {{- end }}
          ports:
            - containerPort: 80
    metadata:
      labels:
        app.kubernetes.io/name: pokertool
        app.kubernetes.io/component: frontend
