apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}-frontend
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "common.labels.standard" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    spec:
      containers:
        {{- with .Values.frontend.image}}
        - image: "{{ .registry }}/{{ .name }}:{{ .tag }}"
        {{- end }}
          name: {{ template "common.names.fullname" . }}-frontend
          ports:
            - containerPort: 80
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: frontend
