{{ if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pokertool-frontend
  labels:
    app.kubernetes.io/name: pokertool
    app.kubernetes.io/component: frontend
spec:
  rules:
    - host: {{ .Values.ingress.domain | required "ingress.domain required" }}
      http:
        paths:
          - backend:
              service:
                name: pokertool-frontend
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.ingress.domain | required "ingress.domain required" }}
      secretName: pokertool-frontend-cert
{{- end }}
