apiVersion: v1
kind: Service
metadata:
  name: pokertool-frontend
  labels:
    app.kubernetes.io/name: pokertool
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: pokertool
    app.kubernetes.io/component: frontend
  ports:
    - port: 80
      targetPort: 80
